### ISSUE TITLE
Add a simple `pyproject.toml`

### ISSUE THREAD

**Issue by LecrisUT** [befeleme/zuul-config-generator#2]
This way we can more easily install via `pip install git+https://github.com/befeleme/zuul-config-generator@main`

And cheers for the tool

**Comment by befeleme** [comment]
Added in https://github.com/befeleme/zuul-config-generator/commit/54cf723b5d3b5bbdea2e12779911a3bc4630c8e9 - please test with the current `main` if it suits you needs.

**Comment by LecrisUT** [comment]
Works like a charm, thank you again for the tool. Maybe you can add a link to it in `fedora-project-config`, or the official documentation of the zuul fedora CI (forgot the page of that)

**Comment by befeleme** [comment]
It's there :)
https://pagure.io/fedora-project-config -> "How to add / maintain your packages list"
https://fedoraproject.org/wiki/Zuul-based-ci#Add_the_repository_into_the_Zuul_configuration

Thank you for feedback!
